name: Pipeline
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests on Linux
        run: |
          echo "Running tests on Linux..."
          echo "Tests completed successfully on Linux!"
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests on Windows
        run: |
          echo "Running tests on Windows..."
          echo "Tests completed successfully on Windows!"
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests on macOS
        run: |
          echo "Running tests on macOS..."
          echo "Tests completed successfully on macOS!"
  deploy:
    needs: [test-linux, test-windows, test-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy demonstration
        run: |
          echo "Starting deployment..."
          echo "Using HOST: my-server.com"
          echo "Using USER: my-username"
          echo "Pretend to copy files to server"
          echo "Pretend to execute remote deployment commands"
          echo "Deployment completed successfully!"
