name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test on Multiple OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] 
        python-version: [3.8, 3.9, 3.10] 
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip # Обновляем pip
          pip install pytest 

      
      - name: Run tests
        run: pytest test_app.py
